config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do

  # Errors routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable', via: :all

  # Route for about-us
  get "/about-us", to: "about#index", as: :about

  # Route for registration
  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  # Route for log-in
  get "/log-in", to: "session#new"
  post "/log-in", to: "session#create"

  # Route to edit password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  # Route to reset password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  # Route for session log out
  delete "/logout", to: "session#destroy"

  # Route for Twitter API callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  # To create the CRUD routes for the twitter accounts
  resources :twitter_accounts
  # ex:
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"

  # To create the CRUD routes for the tweets
  resources :tweets

  # Root Route
  root "main#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            # Send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If an account with that email was found, we have sent to reset your password."
    end

    def edit
        @user = User.find_signed(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to log_in_path, alert: "Your token has expired. Please try again."
    end

    def update
        @user = User.find_signed(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to log_in_path, alert: "Your password was reset successfully. Please log in."
        else
            rendir :edit
        end
    end

    def password_params
        params.require(user).permit(:password, :password_confirmation)
    end
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <%= render "shared/form_errors", form: form %>
    
    <div class="container w-50">
        <div class="mb-3 row justify-content-center">
            <%= form.label :password, class: "form-label col-1 text-start w-25" %>
            <div class="col-6">
                <%= form.password_field :password, class: "form-control col", placeholder: "password" %>
            </div>
        </div>
        <div class="mb-3 row justify-content-center">
            <%= form.label :password_confirmation, class: "form-label col-1 text-start w-25" %>
            <div class="col-6">
                <%= form.password_field :password_confirmation, class: "form-control col", placeholder: "password" %>
            </div>
        </div>
    </div>
    <div>
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>

    <div class="container w-50">
        <div class="my-3 row justify-content-center">
            <%= form.label :Email, class: "form-label col-1 text-start w-25" %>
            <div class="col-6">
                <%= form.text_field :email, class: "form-control col", placeholder: "email@mail.com" %>
            </div>
        </div>
    </div>

    <div>
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>