config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do

  # Errors routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable', via: :all

  # Route for about-us
  get "/about-us", to: "about#index", as: :about

  # Route for registration
  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  # Route for log-in
  get "/log-in", to: "session#new"
  post "/log-in", to: "session#create"

  # Route to edit password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  # Route to reset password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  # Route for session log out
  delete "/logout", to: "session#destroy"

  # Route for Twitter API callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  # To create the CRUD routes for the twitter accounts
  resources :twitter_accounts
  # ex:
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"

  # To create the CRUD routes for the tweets
  resources :tweets

  # Root Route
  root "main#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  # Validation for all the fields:

  # -> For the length of the text
  validates :body, length: { minimum: 1, maximun: 280 }

  # -> For the date to publish to be always present
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 1.hour.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
        TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  # To determine if the tweet was published or not.
  def published?
    # Checks if there is a tweet id saved, returns true or false
    tweet_id? 
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:show, :edit, :update,:destroy]

    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end
    
    def create
        @tweet = Current.user.tweets.new(tweet_params)
 
        if @tweet.save
            redirect_to tweets_path, notice: "Tweet was scheduled successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet was updated successfully!"
        else
            render :edit
        end
    end

    def destroy
        @tweet.destroy
        redirect_to tweets_path, status: :see_other
    end
    
    private
    
    def tweet_params
        params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end
    
    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet, data: { turbo: true }, local: true do |form| %>
    <%= render "shared/form_errors", form: form %>

    <div class="my-3">
        <h4>Tweet content:</h4>
        <%= form.text_area :body, :maxlength => 280, class: "form-control my-3" %>
    </div>

    <div class="d-flex justify-content-between my-3">
        <div class="d-inline-block">
            <h4 class="d-inline-block me-3">Select Twitter account:</h4>
            <div class="d-inline-block">
                <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-select"} %>
            </div>
        </div>
        <div class="d-inline-block">
            <h4 class="d-inline-block me-3">Date to publish:</h4>
            <%= form.datetime_select :publish_at, class:"d-inline-block" %>
        </div>
    </div>

    <hr class="my-3">

    <div class="d-flex justify-content-between">
        <%= form.button "Schedule", class: "btn btn-primary btn-lg button-hover" %>

        <% if form.object.persisted? %>
            <%= link_to "Delete", form.object, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-outline-danger btn-lg" %>
        <% end %>
    </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweets-card card card-body mb-3">
    <div class="d-flex align-items-center">
        <% if tweet.published? %>
            <%= image_tag tweet.twitter_account.image, class: "rounded-circle border border-2 border-primary p-1 border-opacity-50 me-3" %>
            <div class="tweet-info d-flex align-items-start flex-column me-3">
                <div>
                    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank, class: "custom-anchor" %>
                    <span>on (<%= l tweet.publish_at, format: :long, class:"fst-italic" %>):</span>
                </div>
                <div>
                    <span class="tweet-body d-block fst-italic text-black-50 text-break">
                        "<%= tweet.body %>"
                        <%= link_to '<i class="bi bi-trash3-fill"></i>'.html_safe, tweet, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "trash-can" %>
                    </span>
                </div>
            </div>
            <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", class:"view-tweet text-decoration-none ms-auto", target: :_blank %>
        <% else %>
            <%= image_tag tweet.twitter_account.image, class: "rounded-circle border border-2 border-primary p-1 border-opacity-50 me-3" %>
            <div class="d-flex align-items-start flex-column me-3">
                <%= link_to "@#{tweet.twitter_account.username}:", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank, class: "custom-anchor" %>
                <div class="ScheduledTweet">
                    <span class="tweet-body fst-italic text-black-50 text-break">"<%= tweet.body %>"</span>
                    <%= link_to edit_tweet_path(tweet), class: "text-decoration-none" do %>
                        <i class="bi bi-pencil">edit</i>
                    <% end %>
                </div>
            </div>
            <span class="ms-auto">
                Scheduled for <%= l tweet.publish_at, format: :short %>
            </span>
        <% end %>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
        <h1 class="border-bottom border-2 border-opacity-25 border-primary fst-italic me-3">
            Edit a tweet
            <i class="bi bi-twitter"></i>
        </h1>
    </div>    
    <%= render "form", tweet: @tweet %>
</div>

app/views/tweets/index.html.erb
<div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
        <h1 class="border-bottom border-2 border-opacity-25 border-primary fst-italic me-3">
            Tweets
            <i class="bi bi-twitter"></i>
        </h1>
    
        <% if Current.user.twitter_accounts.any? %>
            <%= link_to "Schedule a tweet", new_tweet_path, class: "btn btn-primary button-hover" %>
        <% end %>
    </div>
    
    <% if Current.user.twitter_accounts.none? %>
        <%= button_to "Connect Twitter", "/auth/twitter", data: {turbo: "false"}, method: :post, class:"btn btn-primary button-hover mt-5" %>
    <% end %>
    
    <div class="tweetsContainer">
        <%= render @tweets %>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
        <h1 class="border-bottom border-2 border-opacity-25 border-primary fst-italic me-3">
            Schedule a tweet
            <i class="bi bi-twitter"></i>
        </h1>
    </div>    
    <%= render "form", tweet: @tweet %>
</div>