config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do

  # Errors routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable', via: :all

  # Route for about-us
  get "/about-us", to: "about#index", as: :about

  # Route for registration
  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  # Route for log-in
  get "/log-in", to: "session#new"
  post "/log-in", to: "session#create"

  # Route to edit password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  # Route to reset password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  # Route for session log out
  delete "/logout", to: "session#destroy"

  # Route for Twitter API callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  # To create the CRUD routes for the twitter accounts
  resources :twitter_accounts
  # ex:
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"

  # To create the CRUD routes for the tweets
  resources :tweets

  # Root Route
  root "main#index"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid mail or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/views/session/new.html.erb
<%= form_with url: log_in_path do |form| %>
    <div class="col-8 col-lg-6 col-xl-5 col-xxl-4 mx-auto">
        <div class="container-fluid card px-0">
            <div class="card-header text-center">
                <h2>Log-in to Schedule Tweets!</h2>
            </div>
            <div class="card-body px-5">
                <div class="form-floating">
                    <%= form.text_field :email, class: "form-control", placeholder: "email@mail.com", type:"email" %>
                    <%= form.label :email, "Email", for:"floating-input" %>
                </div>
                <div class="form-floating my-3">
                    <%= form.password_field :password, class: "form-control", placeholder: "password", type:"password" %>
                    <%= form.label :password, "Password", for:"floating-password" %>
                    <%= link_to "Forgot your password?", password_reset_path, class: "d-flex justify-content-end my-2" %>
                </div>
                <div class="d-grid">
                    <%= form.submit "Log in", class: "btn btn-primary button-hover" %>
                </div> 
            </div>           
        </div>
    </div>
<% end %>