config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do

  # Errors routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable', via: :all

  # Route for about-us
  get "/about-us", to: "about#index", as: :about

  # Route for registration
  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  # Route for log-in
  get "/log-in", to: "session#new"
  post "/log-in", to: "session#create"

  # Route to edit password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  # Route to reset password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  # Route for session log out
  delete "/logout", to: "session#destroy"

  # Route for Twitter API callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  # To create the CRUD routes for the twitter accounts
  resources :twitter_accounts
  # ex:
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"

  # To create the CRUD routes for the tweets
  resources :tweets

  # Root Route
  root "main#index"
end

app/views/shared/_darkMode.html.erb
<div id="dark-button" class="d-inline">
    <button type="button" class="btn btn-circle btn-sm" data-action="click->darkmode#themeToggle">
        <i class="bi bi-lightbulb"></i>
    </button>
</div>
    
<div class="dark-switch">
    <!-- Dark Mode Switch: -->
    <input class="switch-input" type="checkbox" id="darkSwitch" data-action="click->darkmode#themeToggle">
    <label class="switch-label" for="darkSwitch">
        <i class="bi bi-moon"></i>
        <i class="bi bi-sun"></i>
        <div id="ball" class='ball' data-darkmode-target="ball"></div>
    </label>
</div>

app/views/shared/_footer.html.erb
<footer class="footer border-top border-dark border-1">
    <%= render partial: "shared/darkMode" %>

    <div class="navbar navbar-fixed-bottom">
        <div class="container d-flex justify-content-center">
            <p id="footerText" class="navbar-text my-auto text-white">Made by Emanuel Rodriguez Bedeman ©</p>
        </div>
    </div>
</footer>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
    <div class="container w-50 alert alert-danger text-start">
    <p>Error!</p>
        <% form.object.errors.full_messages.each do |message| %>
            <div>* <%= message %></div>
        <% end %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg border-bottom border-dark border-1">
    <div class="container-fluid" role="navigation">

        <!-- Navbar Title -->
        <div class="navbar-header" role="navigation">
            <%= link_to tweets_path, class:"navbar-brand h1 me-3" do %>
                <span class="border-bottom">Tweets</span>
                <i class="bi bi-twitter text-white ms-1"></i>
            <% end %>
        </div>

        <!-- Dropdown Navbar Content -->
            <!-- Navbar Button -->
        <button class="button-hover navbar-toggler border-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-nav" aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-nav">
            <!-- Navbar Links -->
            <ul class="nav navbar-nav navbar-left large-navbar-items">
                <hr class="d-lg-none border-white my-1 w-25">
                <div class="vr d-none d-lg-block "></div>
                <li class= "nav-item" id="home">
                    <%= link_to "Home", root_path, class:"nav-link link-hover"%>
                </li>
                <div class="vr d-none d-lg-block "></div>
                <li class= "nav-item" id="about">
                    <%= link_to "About", about_path, class:"nav-link link-hover"%>
                </li>
                <div class="vr d-none d-lg-block "></div>
                <li class= "nav-item" id="twitter-accounts">
                    <%= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link link-hover"%>
                </li>
            </ul>

            <!-- Navbar Session Interactions -->
            <ul class="nav navbar-nav ms-auto">
                <% if Current.user %>

                    <!-- Edit pass and log-out for lg screens -->
                    <div class="d-none d-lg-flex">
                        <li class="nav-item">
                            <%= link_to "Edit Password", password_path, class:"nav-link button-hover border rounded-pill" %>
                        </li>
                        <div class="vr d-none d-lg-block mx-2 p-0"></div>
                        <li class="nav-item">
                            <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-light custom-border button-hover border rounded-pill"%>
                        </li>
                    </div>

                    <!-- Edit pass and log-out for small screens -->
                    <div class="row d-lg-none mt-3">
                        <div class="col d-lg-none text-center">
                            <li class="nav-item">
                                <%= link_to "Edit Password", password_path, class:"nav-link button-hover border rounded-pill" %>
                            </li>
                        </div>
                        <div class="vr d-none d-lg-block mx-2 p-0"></div>
                        <div class="col d-lg-none text-center">
                            <li class="nav-item">
                                <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-block btn-outline-light button-hover border rounded-pill w-100"%>
                            </li>
                        </div>
                    </div>

                <% else %>

                    <!-- Sign up and Log in for lg screens -->
                    <div class="d-none d-lg-flex">
                        <li class="nav-item">
                            <%= link_to "Sign up", sign_up_path, class:"nav-link button-hover border rounded-pill" %>
                        </li>
                        <div class="vr d-none d-lg-block mx-2 p-0"></div>
                        <li class="nav-item">
                            <%= link_to "Log in", log_in_path, class:"nav-link button-hover border rounded-pill" %>
                        </li>
                    </div>

                    <!-- Sign up and Log in for small screens -->
                    <div class="row d-lg-none mt-3">
                        <div class="col d-lg-none text-center">
                            <li class="nav-item">
                                <%= link_to "Sign up", sign_up_path, class:"nav-link button-hover border rounded-pill" %>
                            </li>
                        </div>
                        <div class="col d-lg-none text-center">
                            <li class="nav-item">
                                <%= link_to "Log in", log_in_path, class:"nav-link button-hover border rounded-pill" %>
                            </li>
                        </div>
                    </div>

                <% end %>

            </ul>
        </div>
    </div>
</nav>